# Ruff style: Compliant
# Description:
# This module handles parsing of metadata files generated by the microscope.

import json
import os
from typing import Any, Dict, Optional


def parse_acq_settings(settings_path: str) -> Optional[Dict[str, Any]]:
    """
    Parses the JSON-formatted AcqSettings.txt file.

    Args:
        settings_path: The full path to the AcqSettings.txt file.

    Returns:
        A dictionary containing the parsed metadata, or None if the file
        cannot be read or parsed.
    """
    if not os.path.exists(settings_path):
        print(f"Info: Metadata file not found at {settings_path}")
        return None

    try:
        with open(settings_path) as f:
            data = json.load(f)
            # Extract key parameters and return them in a flat dictionary
            # for easier access.
            params = {
                "num_channels": data.get("numChannels"),
                "voxel_size_z": data.get("stepSizeUm"),
                "save_name_prefix": data.get("saveNamePrefix"),
            }
            print(f"Successfully parsed metadata from {settings_path}")
            return params
    except (json.JSONDecodeError, IOError) as e:
        print(f"Warning: Could not read or parse AcqSettings.txt: {e}")
        return None
